### ISSUE TITLE
Permissions Issue with `pod try` when the pod has third party dependencies

### ISSUE THREAD

**Issue by simonrice** [CocoaPods/cocoapods-try#32]
### Command

```
/Users/simon/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?

I ran `pod try PNChart` (also occurs with `pod try {MSCollectionViewCalendarLayout, Mantle-HAL, https://github.com/kevinzhow/PNChart.git, etc.)

* What did you expect to happen?

There shouldn't be any complaints, Xcode opens & I can try out said pod.

* What happened instead?

There is a permissions error, as highlighted in this template that you've kindly provided.  Xcode still opens, but the PNChart sample project doesn't build due to `Pods/Manifest.lock` missing.  The same issue occurred when I tried out `pod try https://github.com/kevinzhow/PNChart.git`.  I also tried it out MSCollectionViewCalendarLayout and Mantle-HAL and this same issue occurred.

From my deductions, it seems like this issue occurs with pods with third party non-test dependencies as similar commands for AFNetowrking, Mantle and SRMonthPicker (head version only as *cough* I need to update it) - these libraries lack pod dependencies.

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/simon/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5ae10957b2084d13ca34e949469433d1f5315edc
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
pod 'UICountingLabel','~> 1.2.0'

target :PNChartTests do
    pod 'Expecta'
end
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /private/tmp/CocoaPods/Try/PNChart/Podfile.lock
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `initialize'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `write_to_disk'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:604:in `block in write_lockfiles'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:603:in `write_lockfiles'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:136:in `block in generate_pods_project'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:129:in `generate_pods_project'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:97:in `install!'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/simon/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/simon/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/simon/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/simon/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/simon/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
This should be fixed on CocoaPods master, I believe.

**Comment by simonrice** [comment]
And so it is :) cheers!
