### ISSUE TITLE
`pod try` throws Permission denied error

### ISSUE THREAD

**Issue by irace** [CocoaPods/cocoapods-try#37]
Hey all, any ideas why I might be getting the following error?

```
tumblr-MacBookPro-2a5158:deleteme bryan$ pod try XExtensionItem
```

Updating spec repositories

Trying XExtensionItem
Analyzing dependencies
Fetching podspec for `XExtensionItem` from `../`

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3a499560f72fc75721439a542afb8d85fb8b0ca7
               Tumblr - git@github.ewr01.tumblr.net:TumblrMobile/Podspecs.git @ f3bf64ce514cc0c27d7bd9e25cd557c3ea9e99d3
               tumblr-tumblrmobile-podspecs - https://github.ewr01.tumblr.net/TumblrMobile/Podspecs.git @ f3bf64ce514cc0c27d7bd9e25cd557c3ea9e99d3
               tumblr-tumblrmobile-podspecs-1 - git://github.ewr01.tumblr.net/TumblrMobile/Podspecs.git @ f3bf64ce514cc0c27d7bd9e25cd557c3ea9e99d3
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-trunk       : 0.3.1
cocoapods-try         : 0.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'App', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end

target 'Extension', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end
```

### Error

```
Errno::EACCES - Permission denied - /private/tmp/CocoaPods/Try/XExtensionItem/Example/Pods/Local Podspecs/XExtensionItem.podspec.json
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/sandbox.rb:257:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/sandbox.rb:257:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/sandbox.rb:257:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/sandbox.rb:257:in `store_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/abstract_external_source.rb:147:in `store_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:190:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:112:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+-+%2Fprivate%2Ftmp%2FCocoaPods%2FTry%2FXExtensionItem%2FExample%2FPods%2FLocal+Podspecs%2FXExtensionItem.podspec.json&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Opening '/private/tmp/CocoaPods/Try/XExtensionItem/Example/XExtensionItemExample.xcworkspace'
```

**Comment by segiddins** [comment]
This is likely fixed on `master`, since we now use `Dir.tmpdir` instead of blindly using `tmp`, which you may not have write permissions for?

**Comment by orta** [comment]
closing, @segiddins' answer feels reasonable
