### ISSUE TITLE
"Error loading the plugin" when running any 1.0.0 beta 3 pod command

### ISSUE THREAD

**Issue by deemadden** [CocoaPods/cocoapods-try#50]
Greetings,
I updated my Cocoapods gem from 0.39 to 1.0.0 beta 3, after completely wiping all of my gems and installing from scratch.  After installing, I see the following error every time I run any pod command:

---------------------------------------------
```
Error loading the plugin `cocoapods-try-1.0.0.beta.3`.

NameError - uninitialized constant Pod::Command::Try::RepoUpdate
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:10:in `<class:Try>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:9:in `<class:Command>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:6:in `<module:Pod>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:5:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```
---------------------------------------------

I should note that this doesn't appear to impair any of the basic commands in any way thus far.

I'm on OSX El Capitan 10.11.3

If there is any other info you need, let me know.  Thanks!

**Comment by segiddins** [comment]
@mrackwitz I'm guessing this was caused by https://github.com/CocoaPods/cocoapods-try/pull/49 -- we need to make sure that whatever file defines `RepoUpdate` is required

**Comment by deemadden** [comment]
@segiddins I'm stuck on beta 3 for the short term due to problems with one of our internal pods.  I do see that I'm getting beta 3 of try when I do a `gem list`:

```
cocoapods (1.0.0.beta.3)
cocoapods-core (1.0.0.beta.3)
cocoapods-deintegrate (1.0.0.beta.1)
cocoapods-downloader (1.0.0.beta.2)
cocoapods-plugins (1.0.0.beta.1)
cocoapods-search (1.0.0.beta.1)
cocoapods-stats (1.0.0.beta.3)
cocoapods-trunk (1.0.0.beta.2)
cocoapods-try (1.0.0.beta.3)

```

**Comment by segiddins** [comment]
`gem uninstall cocoapods-try && gem install cocoapods-try -v 1.0.0.beta.2` should do it.

**Comment by deemadden** [comment]
That did it!  Thanks @segiddins !
